variable "vpc_cidr_block" {}
variable "instance_tenancy" {}
variable "vpc_name" {}
variable "public_subnet_cidr" {}
variable "public_sub_az" {}
variable "map_public_ip_on_launch" {}
variable "public_subnet_name" {}
variable "public_subnet_tags" {}
variable "private_subnet_cidr" {}
variable "private_sub_az" {}
variable "private_subnet_tags" {}
variable "igw_name" {}
variable "elasticip_name" {}
variable "public_rt_tag" {}
variable "private_rt_tag" {}
variable "public_nacl_ingress_rules" {}
variable "public_nacl_egress_rules" {}
variable "public_nacl_tags" {}
variable "frontend_nacl_ingress_rules" {}
variable "frontend_nacl_egress_rules" {}
variable "frontend_nacl_tags" {}
variable "application_nacl_ingress_rules" {}
variable "application_nacl_egress_rules" {}
variable "application_nacl_tags" {}
variable "database_nacl_ingress_rules" {}
variable "database_nacl_egress_rules" {}
variable "database_nacl_tags" {}
variable "alb_sg_name" {}
variable "alb_sg_tag" {}
variable "alb_ingress_rule" {}
variable "alb_egress_rule" {}
variable "alb_name" {}
variable "alb_internal" {}
variable "alb_balancer_type" {}
